#!/bin/bash

pkgs=(
	neovim				# editor
	i3-gaps				# tilling window manager
	polybar				# status bar
	dunst				# notification manager
	rofi				# menu
	alacritty			# terminal emulator
	adobe-source-code-pro-fonts	# main fonts
	udiskie				# disk automounter
	starship			# shell prompt
	ttf-font-awesome		# fake icons
	pulseaudio			# sound server
	pulseaudio-alsa			# sound server integration with alsa
	pavucontrol			# volume control
)

yay -Syu --needed "${pkgs[@]}"
